---
- hosts: server1
  vars:
    new_username: djangoadmin16
  tasks:

  - name: Create a login user
    user:
      name: '{{ new_username }}'
      password: '$6$F4NWXRFtSdCi8$DsB5vvMJYusQhSbvGXrYDXL6Xj37MUuqFCd4dGXdKd6NyxT3lpdELN07/Kpo7EjjWnm9zusFg/LLFv6oc.ynu/'
      groups: sudo   # Empty by default.
      state: present
      shell: /bin/bash       # Defaults to /bin/bash
      system: no             # Defaults to no
      createhome: yes        # Defaults to yes
      home: /home/{{ new_username }}  # Defaults to /home/<username>

  - name: change sudo users - no need present password
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%sudo'
      line: '%sudo ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

#  - name: Create a .ssh directory
#    command: mkdir /home/'{{ new_username }}'/.ssh

  - name: Ansible check directory.
    stat:
      path: /home/{{ new_username }}/.ssh
    register: my_folder

  - name: Create a .ssh directory
    file:
      path: /home/{{ new_username }}/.ssh
      state: directory
      mode: 0755
      #group: root
      #owner: '{{ new_username }}'
    when: my_folder.stat.exists == false

  - name: Copy authorized_keys file
    command: cp ~/.ssh/authorized_keys /home/{{ new_username }}/.ssh/authorized_keys

  - name: Change ACL permissions
    command: setfacl -m u:{{ new_username }}:r /home/{{ new_username }}/.ssh/authorized_keys
