---
- name: Improve Server Security Settings
  hosts: server1
  gather_facts: false

  tasks:
    - name: disable password authentication
      lineinfile:
        path: "{{ item }}"
        regex: ^(# *)?PasswordAuthentication
        line: PasswordAuthentication no
      loop:
        - /etc/ssh/sshd_config

    - name: disable root login
      lineinfile:
        path: "{{ item }}"
        regex: ^(# *)?PermitRootLogin
        line: PermitRootLogin no
      loop:
        - /etc/ssh/sshd_config

    - name: restart sshd
      service: name=sshd state=restarted

    - name: Enable UFW and allow OpenSSH
      ufw:
        rule: allow
        name: OpenSSH
        state: enabled
