---
- name: Software Updates
  hosts: server1

  tasks:

    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install python3-pip
      become: true
      apt:
        name: python3-pip
        state: latest
        update_cache: yes

    - name: Install python3-dev
      become: true
      apt:
        name: python3-dev
        state: latest
        update_cache: yes

    - name: Install libpq-dev
      become: true
      apt:
        name: libpq-dev
        state: latest
        update_cache: yes

    - name: Install postgresql
      become: true
      apt:
        name: postgresql
        state: latest
        update_cache: yes

    - name: Install postgresql-contrib
      become: true
      apt:
        name: postgresql-contrib
        state: latest
        update_cache: yes

    - name: Install curl
      become: true
      apt:
        name: curl
        state: latest
        update_cache: yes

    - name: Install nginx
      become: true
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Install python3-psycopg2
      become: true
      apt:
        name: python3-psycopg2
        state: latest
        update_cache: yes

    - name: Install python3-venv
      become: true
      apt:
        name: python3-venv
        state: latest
        update_cache: yes
