---
- name: Create Database And User (D-0/3)
  hosts: web_server1

  tasks:

    - name: create database (D-1/3)
      become: true
      become_user: postgres
      postgresql_db:
            name: '{{ db_database }}'
            encoding: UTF-8

    - name: create user (D-2/3)
      postgresql_user: name={{ db_user }} password={{ db_password }}
      become: true
      become_user: postgres

    - name: grant all priviledges on database to user (D-3/3)
      become: true
      become_user: postgres
      postgresql_privs:
        db: '{{ db_database }}'
        privs: ALL
        type: database
        objs: '{{ db_database }}'
        role: '{{ db_user }}'
