---
- hosts: local
  name: Enable SSH-Agent And Clone Files Into Remote Server (E-0/3)
  tasks:

  - name: enable ssh agent and add id_ansible (E-1/3)
    shell: |
      eval "$(ssh-agent)"
      ssh-add ~/.ssh/id_ansible

- hosts: web_server1
  #name: git pull
  vars:
    dir_project: pyapps
    new_username: djangoadmin16
    #git_repo: https://github.com/adminstratserver/ONT_V47.git
    git_repo: https://github.com/adminstratserver/Devops.git

  tasks:

  - name: clone repository from github (E-2/3)
    git:
      repo: '{{ git_repo }}'
      dest: /home/{{ new_username }}/{{ dir_project }}
      refspec: '+refs/pull/*:refs/heads/*'

  - name: create a venv environment inside pyapps directory (E-3/3)
    become: true
    command: python3 -m venv /home/{{ new_username }}/{{ dir_project }}/venv
