---
- hosts: server1
  name: Install Packages from requirements.txt, ngunicorn setup at remote server (F-0/6)
  vars:
    new_username: djangoadmin16
    dir_project: pyapps
    app_dir: ONTV_Files

  tasks:

  - name: install dependencies (F-1/6)
    become: true
    pip:    requirements=/home/{{ new_username }}/{{ dir_project }}/{{ app_dir }}/requirements4.txt
            virtualenv=/home/{{ new_username }}/{{ dir_project }}/venv
            virtualenv_python=python3.6.9

  - name: copy gunicorn.socket file (F-2/6)
    become: true
    command: cp /home/{{ new_username }}/{{ dir_project }}/gunicorn/gunicorn.socket /etc/systemd/system/gunicorn.socket

  - name: copy gunicorn.service file (F-3/6)
    become: true
    command: cp /home/{{ new_username }}/{{ dir_project }}/gunicorn/gunicorn.service /etc/systemd/system/gunicorn.service


  - name: edit gunicorn.services User (F-4/6)
    lineinfile:
      path: /etc/systemd/system/gunicorn.service
      regexp: '^User='
      line: User={{ new_username }}

  - name: edit gunicorn.services WorkingDirectory (F-5/6)
    lineinfile:
      path: /etc/systemd/system/gunicorn.service
      regexp: '^WorkingDirectory='
      line: WorkingDirectory=/home/{{ new_username }}/{{ dir_project }}/{{ app_dir }}

  - name: edit gunicorn.services ExecStart (F-6/6)
    lineinfile:
      path: /etc/systemd/system/gunicorn.service
      regexp: '^ExecStart='
      line: ExecStart=/home/{{ new_username }}/{{ dir_project }}/venv/bin/gunicorn \
